### ISSUE TITLE
Do you have a discord?

### ISSUE THREAD

**Issue by CheatMaker** [Lefraudeur/RiptermsGhost#2]
I'm trying to make silent kill aura by patching the d0 and d1 local vars in onWalkingUpdate() in entityplayersp

**Comment by Lefraudeur** [comment]
yeah I have discord, it's just
lefraudeur
I don't know if it works since they remove the tag
or try
lefraufeur#2383

**Comment by CheatMaker** [comment]
Thanks so much bro

**Comment by CheatMaker** [comment]
sent freind rq
