### ISSUE TITLE
Hello, how did you generate that mappings

### ISSUE THREAD

**Issue by FBMNBAWA** [Lefraudeur/RiptermsGhost#32]
Hello, how did you generate that mappings，pls tell me

**Comment by Lefraudeur** [comment]
It was done manually, it's a custom json mapping format I created.
I'm currently writing a program to automate that process.
But for now, I manually read the source code :
https://github.com/Marcelektro/MavenMCP-1.8.9
https://github.com/Hexeption/MCP-Reborn
And mappings file, depending on the version :
https://piston-meta.mojang.com/mc/game/version_manifest_v2.json (for 1.16.5+)
https://github.com/MinecraftForge/MCPConfig (for forge)
https://github.com/ModCoderPack/mcpbot (for older versions)
You can find these almost everywhere, there is also a bot to search for mappings in the forge discord server
https://discord.neoforged.net/
Or a cool website :
https://wagyourtail.xyz/Projects/MinecraftMappingViewer/App
