### ISSUE TITLE
1.18.2 not working

### ISSUE THREAD

**Issue by Lefraudeur** [Lefraudeur/RiptermsGhost#67]
looks like 1.18.2 is a little bit different from 1.17.1
make it a seperate version with seperate mappings
or remove support for 1.18.2

**Comment by LadinFors** [comment]
> 1.18.2, 1.17.1'den biraz farklı gibi görünüyor, onu ayrı eşlemelerle ayrı bir sürüm haline getirin veya 1.18.2 desteğini kaldırın

Bro Will You Add Mapping to Minecraft Vanilla 1.8.9? And Do You Have a Discord Address?

**Comment by Lefraudeur** [comment]
> > 1.18.2, 1.17.1'den biraz farklı gibi görünüyor, onu ayrı eşlemelerle ayrı bir sürüm haline getirin veya 1.18.2 desteğini kaldırın
> 
> Bro Will You Add Mapping to Minecraft Vanilla 1.8.9? And Do You Have a Discord Address?

lefraudeur
or lefraudeur#2383

**Comment by Lefraudeur** [comment]
removed 1.18.2 for now
