### ISSUE TITLE
Doesn't work in Minecraft 1.7.10 jre8

### ISSUE THREAD

**Issue by Kamen-akio** [Lefraudeur/RiptermsGhost#80]

**Comment by Kamen-akio** [comment]
![image](https://github.com/Lefraudeur/RiptermsGhost/assets/77380048/a461eeae-a437-4bf5-a668-e001894cda02)

**Comment by arm4xlll** [comment]
add modelview to mapper

**Comment by Lefraudeur** [comment]
who said it works bruh
